# Generated by Django 4.1.3 on 2022-11-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiModel',
        ),
    ]
